### PR TITLE
New formatted READ.ME

### PR DESCRIPTION
**Pull request by EinProfispieler**
##Result
----------

root@pi4:~/iotop# make -f Makearm64 
DE bld/xxxid_info.o
CC bld/xxxid_info.o
DE bld/view_batch.o
CC bld/view_batch.o
DE bld/checks.o
CC bld/checks.o
DE bld/view_curses.o
CC bld/view_curses.o
DE bld/main.o
CC bld/main.o
DE bld/views.o
CC bld/views.o
DE bld/arr.o
CC bld/arr.o
DE bld/vmstat.o
CC bld/vmstat.o
DE bld/utils.o
CC bld/utils.o
DE bld/ioprio.o
CC bld/ioprio.o
LD iotop

root@pi4:~/iotop# ./iotop -h
Usage: ./iotop [OPTIONS]

DISK READ and DISK WRITE are the block I/O bandwidth used during the sampling
period. SWAPIN and IO are the percentages of time the thread spent respectively
while swapping in and waiting on I/O more generally. PRIO is the I/O priority
at which the thread is running (set using the ionice command).

Controls: left and right arrows to change the sorting column, r to invert the
sorting order, o to toggle the --only option, p to toggle the --processes
option, a to toggle the --accumulated option, i to change I/O priority, q to
quit, any other key to force a refresh.

Options:
  -v, --version         show program's version number and exit
  -h, --help            show this help message and exit
  -o, --only            only show processes or threads actually doing I/O
  -b, --batch           non-interactive mode
  -n NUM, --iter=NUM    number of iterations before ending [infinite]
  -d SEC, --delay=SEC   delay between iterations [1 second]
  -p PID, --pid=PID     processes/threads to monitor [all]
  -u USER, --user=USER  users to monitor [all]
  -P, --processes       only show processes, not all threads
  -a, --accumulated     show accumulated I/O instead of bandwidth
  -k, --kilobytes       use kilobytes instead of a human friendly unit
  -t, --time            add a timestamp on each line (implies --batch)
  -c, --fullcmdline     show full command line
  -1, --hide-pid        hide PID/TID column
  -2, --hide-prio       hide PRIO column
  -3, --hide-user       hide USER column
  -4, --hide-read       hide DISK READ column
  -5, --hide-write      hide DISK WRITE column
  -6, --hide-swapin     hide SWAPIN column
  -7, --hide-io         hide IO column
  -8, --hide-graph      hide GRAPH column
  -9, --hide-command    hide COMMAND column
  -q, --quiet           suppress some lines of header (implies --batch)
  -x, --dead-x          show dead processes/threads with letter x

### CODE REVIEW

**Comment by bbonev** [comment]
Thanks for the suggestions; please remove the Makearm64 addition from this commit (see my comment on the separate PR).

I have noticed that for some reason folding on arm64 build instructions fold all the following section; please fix that and I will review again and merge it.

**Comment by EinProfispieler** [comment]
Sorry bbonev, will fix it right up. my birthday today, alot incoming messages.

**Comment by EinProfispieler** [comment]
Done, i will look into it  see if it works properly and get back to you. also that's a great idea to make additional into existed Makefile. will follow this method.

**Comment by bbonev** [comment]
Huh, happy birthday! Enjoy your party instead of doing this :)

**Pull request merged**
