### PR TITLE
Makefile for Arm64

### PR DESCRIPTION
**Pull request by EinProfispieler**
Raspberry Pi or other Arm linux system.

### CODE REVIEW

**Comment by EinProfispieler** [comment]
Also made a reformat READ.ME. with centos and arm64 system install guide.

**Comment by EinProfispieler** [comment]
##Result
----------

root@pi4:~/iotop# make -f Makearm64 
DE bld/xxxid_info.o
CC bld/xxxid_info.o
DE bld/view_batch.o
CC bld/view_batch.o
DE bld/checks.o
CC bld/checks.o
DE bld/view_curses.o
CC bld/view_curses.o
DE bld/main.o
CC bld/main.o
DE bld/views.o
CC bld/views.o
DE bld/arr.o
CC bld/arr.o
DE bld/vmstat.o
CC bld/vmstat.o
DE bld/utils.o
CC bld/utils.o
DE bld/ioprio.o
CC bld/ioprio.o
LD iotop


root@pi4:~/iotop# ./iotop -h
Usage: ./iotop [OPTIONS]

DISK READ and DISK WRITE are the block I/O bandwidth used during the sampling
period. SWAPIN and IO are the percentages of time the thread spent respectively
while swapping in and waiting on I/O more generally. PRIO is the I/O priority
at which the thread is running (set using the ionice command).

Controls: left and right arrows to change the sorting column, r to invert the
sorting order, o to toggle the --only option, p to toggle the --processes
option, a to toggle the --accumulated option, i to change I/O priority, q to
quit, any other key to force a refresh.

Options:
  -v, --version         show program's version number and exit
  -h, --help            show this help message and exit
  -o, --only            only show processes or threads actually doing I/O
  -b, --batch           non-interactive mode
  -n NUM, --iter=NUM    number of iterations before ending [infinite]
  -d SEC, --delay=SEC   delay between iterations [1 second]
  -p PID, --pid=PID     processes/threads to monitor [all]
  -u USER, --user=USER  users to monitor [all]
  -P, --processes       only show processes, not all threads
  -a, --accumulated     show accumulated I/O instead of bandwidth
  -k, --kilobytes       use kilobytes instead of a human friendly unit
  -t, --time            add a timestamp on each line (implies --batch)
  -c, --fullcmdline     show full command line
  -1, --hide-pid        hide PID/TID column
  -2, --hide-prio       hide PRIO column
  -3, --hide-user       hide USER column
  -4, --hide-read       hide DISK READ column
  -5, --hide-write      hide DISK WRITE column
  -6, --hide-swapin     hide SWAPIN column
  -7, --hide-io         hide IO column
  -8, --hide-graph      hide GRAPH column
  -9, --hide-command    hide COMMAND column
  -q, --quiet           suppress some lines of header (implies --batch)
  -x, --dead-x          show dead processes/threads with letter x

**Comment by bbonev** [comment]
I think that it is best to add a conditional in the existing Makefile instead of adding a new Makefile.

BTW. gcc options `-mno-strict-align` and `-mno-stackrealign` do completely different things...

See this: https://github.com/bbonev/iotop/commit/8809ffefc6c99ee5054c684256d8e3cbaa1658ae

**Comment by EinProfispieler** [comment]
> I think that it is best to add a conditional in the existing Makefile instead of adding a new Makefile.
> 
> BTW. gcc options `-mno-strict-align` and `-mno-stackrealign` do completely different things...
> 
> See this: [bbonev@8809ffe](https://github.com/bbonev/iotop/commit/8809ffefc6c99ee5054c684256d8e3cbaa1658ae)

I will look into it , for now this argument just make it works on RPi4, i will see it through and add a condition in existed Makefile. Thank you.

**Comment by KaMyKaSii** [comment]
@EinProfispieler could you provide me with a static binary so I can test it on Android? Thank you

**Comment by bbonev** [comment]
You can try this:

`make clean && make -j LDFLAGS=-static`

There will be warnings:

```
/usr/bin/ld: /tmp/iotop.W5AJ0E.ltrans0.ltrans.o: in function `view_curses':
<artificial>:(.text+0x5245): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/iotop.W5AJ0E.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x14a): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

```
If there is no big difference in glibc, then it may work.

If it does not, then it can be fixed by replacing the above two functions in the code and thus disabling uid to username translations...

**Pull request closed without merging**
